dbt_earthquake_project: # تأكد باللي هذا الإسم مطابق للـ name داخل dbt_project.yml
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: dbt
      location: US
      threads: 4
      timeout_seconds: 300
      
      # ── 🎯 الـتركيب الـميكانيكي للـ مفاتيح لداخل الـ dbt ──────────────────
      keyfile_json:
        type: "service_account"
        project_id: "{{ env_var('GCP_PROJECT') }}"
        private_key_id: "{{ env_var('GCP_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('GCP_PRIVATE_KEY') }}"
        client_email: "{{ env_var('GCP_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('GCP_CLIENT_ID') }}"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        # هنا الـ dbt يدمج الإيميل حركياً لـ توليد الـ رابط النيتيف
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/{{ env_var('GCP_CLIENT_EMAIL') | urlencode }}"
        universe_domain: "googleapis.com" # السطر الأخير الظاهر في الصورة تاعك

  target: dev